---
title: 'Project 2: Modeling, Testing, and Predicting'
author: "Mina Attia"
date: '11/22/2019'
output:
  pdf_document:
    toc: yes
  html_document:
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
---



<div id="introduction" class="section level1">
<h1>Introduction</h1>
<p>I chose to work with the veteran dataset since it relates to lung cancer, which is a sector of medicine that interests me. The dataset is the Veterans’ Administrations Lung Cancer study and consists of randomized trial for veterans that explores two types of treatment for lung cancer. It contains variables such as cancer cell type, survival time, karno score (higher = better overall health), diagnosis time, age, and prior therapy. The trt variable is either the standard treatment regimen or the test regimen. The celltype variable describes the type of cancerous cell (squamous, smallcell, adeno, or large). The rest of the variables include time (survial time in days), censoring status (dead or alive), karnofspy performance score (quantifies cancer patients’ general health and activities of daily life; higher score = better overall response to treatment), diagtime (months from diagnosis to randomisation), age (in years), and prior therary (0=no, 10=yes).</p>
<pre class="r"><code>data(package = .packages(all.available = TRUE))
library(tidyverse)
library(dplyr)
library(survival) 
data(&quot;veteran&quot;) 
?veteran</code></pre>
<pre class="r"><code>##Question 1

manova1&lt;-manova(cbind(diagtime,time,karno,age)~celltype, data=veteran) 

summary(manova1)</code></pre>
<pre><code>## Df Pillai approx F num Df den Df Pr(&gt;F)
## celltype 3 0.2077 2.4546 12 396 0.004266 **
## Residuals 133
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>summary.aov(manova1)</code></pre>
<pre><code>## Response diagtime :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## celltype 3 466.3 155.44 1.3922 0.248
## Residuals 133 14849.7 111.65
##
## Response time :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## celltype 3 478636 159545 7.2955 0.0001446 ***
## Residuals 133 2908596 21869
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response karno :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## celltype 3 2519 839.57 2.1434 0.09777 .
## Residuals 133 52097 391.71
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response age :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## celltype 3 258 86.001 0.77 0.5128
## Residuals 133 14855 111.693</code></pre>
<pre class="r"><code>pairwise.t.test(veteran$time,veteran$celltype, p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  veteran$time and veteran$celltype 
## 
##           squamous smallcell adeno  
## smallcell 0.00015  -         -      
## adeno     0.00046  0.83213   -      
## large     0.36977  0.00890   0.01243
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>veteran%&gt;% group_by(celltype)%&gt;% summarise(mean(time))</code></pre>
<pre><code>## # A tibble: 4 x 2
##   celltype  `mean(time)`
##   &lt;fct&gt;            &lt;dbl&gt;
## 1 squamous         200. 
## 2 smallcell         71.7
## 3 adeno             64.1
## 4 large            166.</code></pre>
<pre class="r"><code>a &lt;- 1-((1-0.05)^11)
a</code></pre>
<pre><code>## [1] 0.4311999</code></pre>
<pre class="r"><code>b&lt;- 0.05/11
b</code></pre>
<pre><code>## [1] 0.004545455</code></pre>
<p>The following tets were conducted: 1 MANOVA, 4 ANOVAS, and 6 post-hoc t-tests (11 tests in total). The probability of at least one type I error (if unadjusted) is 0.4311999. The adjusted significance level (bonferroni correction) is 0.004545455. My MANOVA was significant (p-val=0.004266) and I ran four univariate ANOVA tests, one of which was significant for my time variable (p-value = 0.0001446). Mean survival time differed significantly across different cancer cell types for VA cancer patients (significant difference in mean survival time between squamous and smallcell (p-val = 0.00015) &amp; squamous and adeno cell types (p-val = 0.00046) after adjusting the significance level). The MANOVA assumptions include random sample and independent observations, multivariate normality of DVs, homogeneity of within-group covariance matrices, linear relationships among DVs, no extreme univariate or multivariate outliers, and no multicollinearity; it is very likely that some of these assumptions were too difficult to meet, such as no extreme univariate or multivariate outliers.</p>
<pre class="r"><code>##Question 2

library(vegan)


dists&lt;-veteran%&gt;%select(karno, time)%&gt;%dist() 


adonis(dists~celltype,data=veteran)</code></pre>
<pre><code>##
## Call:
## adonis(formula = dists ~ celltype, data = veteran)
##
## Permutation: free
## Number of permutations: 999
##
## Terms added sequentially (first to last)
##
## Df SumsOfSqs MeanSqs F.Model R2 Pr(&gt;F)
## celltype 3 481155 160385 7.2048 0.1398 0.001 ***
## Residuals 133 2960692 22261 0.8602
## Total 136 3441848 1.0000
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>table(veteran$celltype)</code></pre>
<pre><code>## 
##  squamous smallcell     adeno     large 
##        35        48        27        27</code></pre>
<pre class="r"><code>SST&lt;- sum(dists^2)/137

SSW&lt;-veteran%&gt;%group_by(celltype)%&gt;%select(karno,time)%&gt;%
 do(d=dist(.[2:3],&quot;euclidean&quot;))%&gt;%ungroup()%&gt;%
 summarize(sum(d[[1]]^2)/35 + sum(d[[2]]^2)/48+ sum(d[[3]]^2)/27+sum(d[[4]]^2)/27)%&gt;% pull
F_obs&lt;-((SST-SSW)/3)/(SSW/133)
F_obs</code></pre>
<pre><code>## [1] 7.204805</code></pre>
<pre class="r"><code>Fs&lt;-replicate(1000,{
new&lt;-veteran%&gt;%mutate(celltype=sample(celltype))
SST2&lt;- sum(dists^2)/137
  
  
SSW2&lt;-new%&gt;%group_by(celltype)%&gt;%select(karno,time)%&gt;%
 do(d=dist(.[2:3],&quot;euclidean&quot;))%&gt;%ungroup()%&gt;%
 summarize(sum(d[[1]]^2)/35 + sum(d[[2]]^2)/48+ sum(d[[3]]^2)/27+sum(d[[4]]^2)/27)%&gt;%pull
((SST2-SSW2)/3)/(SSW2/133)})

mean(Fs&gt;F_obs)</code></pre>
<pre><code>## [1] 0</code></pre>
<pre class="r"><code>{hist(Fs,prob = T); abline(v=F_obs, col=&quot;red&quot;)}</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-3-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>ggplot(veteran,aes(time,fill=celltype))+geom_histogram(bins=7)+facet_wrap(~celltype,ncol=2) +theme(legend.position = &quot;none&quot;)</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-3-2.png" width="768" style="display: block; margin: auto;" />
My null hypothesis is that there is no significant difference in mean survival time (in days) and karnofspy performance scores across different cancerous cell types. My alternative hypothesis is that there is a significant difference in mean survival time (in days) and karnofspy performance scores across different cancerous cell types. My PERMANOVA test displays that there is a significant difference in mean survival time (in days) and karnofspy performance scores across different cancerous cell types (adonis p-val = .001, calculated p-val = 0). My observed F value of 7.204805 is greater than my null distribution of F (reference Histogram of Fs above).</p>
<pre class="r"><code>##Question 3

veteran$diagtime_c&lt;-veteran$diagtime-mean(veteran$diagtime) 


veteran$karno_c&lt;-veteran$karno-mean(veteran$karno)

fit&lt;-lm(time ~ diagtime_c * karno_c, data=veteran)

summary(fit)</code></pre>
<pre><code>##
## Call:
## lm(formula = time ~ diagtime_c * karno_c, data =
veteran)
##
## Residuals:
## Min 1Q Median 3Q Max
## -167.46 -78.84 -33.46 15.07 835.26
##
## Coefficients:
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 123.37494 12.81911 9.624 &lt; 2e-16 ***
## diagtime_c 1.09409 1.59505 0.686 0.494
## karno_c 3.08128 0.64333 4.790 4.39e-06 ***
## diagtime_c:karno_c 0.04505 0.06418 0.702 0.484
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Residual standard error: 147.2 on 133 degrees of freedom
## Multiple R-squared: 0.1494, Adjusted R-squared: 0.1302
## F-statistic: 7.784 on 3 and 133 DF, p-value: 7.927e-05</code></pre>
<pre class="r"><code>mean&lt;-predict(fit,veteran)

ggplot(veteran,aes(karno_c,diagtime_c))+geom_point()+geom_line(data=veteran,aes(y=mean))</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-4-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>library(lmtest)
bptest(fit)</code></pre>
<pre><code>## 
##  studentized Breusch-Pagan test
## 
## data:  fit
## BP = 4.2594, df = 3, p-value = 0.2348</code></pre>
<pre class="r"><code>resids&lt;-fit$residuals
fitvals&lt;-fit$fitted.values
ggplot()+geom_point(aes(fitvals,resids))+geom_hline(yintercept=0, color=&#39;red&#39;)</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-4-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>ggplot()+geom_histogram(aes(resids), bins=20)</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-4-3.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>ks.test(resids, &quot;pnorm&quot;, mean=0, sd(resids))</code></pre>
<pre><code>## 
##  One-sample Kolmogorov-Smirnov test
## 
## data:  resids
## D = 0.22135, p-value = 2.954e-06
## alternative hypothesis: two-sided</code></pre>
<pre class="r"><code>library(sandwich)
summary(fit)$coef[,1:2]</code></pre>
<pre><code>##                        Estimate Std. Error
## (Intercept)        123.37494111 12.8191102
## diagtime_c           1.09408916  1.5950464
## karno_c              3.08127546  0.6433269
## diagtime_c:karno_c   0.04505009  0.0641833</code></pre>
<pre class="r"><code>coeftest(fit, vcov = vcovHC(fit))[,1:2]</code></pre>
<pre><code>##                        Estimate  Std. Error
## (Intercept)        123.37494111 13.30125926
## diagtime_c           1.09408916  1.51374065
## karno_c              3.08127546  0.67525141
## diagtime_c:karno_c   0.04505009  0.05686977</code></pre>
<pre class="r"><code>(sum((veteran$time-mean(veteran$time))^2)-sum(fit$residuals^2))/sum((veteran
$time-mean(veteran$time))^2)</code></pre>
<pre><code>## [1] 0.1493513</code></pre>
<pre class="r"><code>fitted_2&lt;-lm(time ~ diagtime_c + karno_c, data=veteran)
summary(fitted_2)</code></pre>
<pre><code>##
## Call:
## lm(formula = time ~ diagtime_c + karno_c, data =
veteran)
##
## Residuals:
## Min 1Q Median 3Q Max
## -176.32 -77.02 -35.75 12.03 835.26
##
## Coefficients:
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 121.6277 12.5513 9.690 &lt; 2e-16 ***
## diagtime_c 0.3646 1.2076 0.302 0.763
## karno_c 3.0407 0.6395 4.755 5.06e-06 ***
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Residual standard error: 146.9 on 134 degrees of freedom
## Multiple R-squared: 0.1462, Adjusted R-squared: 0.1335
## F-statistic: 11.47 on 2 and 134 DF, p-value: 2.517e-05</code></pre>
<pre class="r"><code>nullfit&lt;-lm(time ~ diagtime_c, data=veteran)
summary(nullfit)</code></pre>
<pre><code>##
## Call:
## lm(formula = time ~ diagtime_c, data = veteran)
##
## Residuals:
## Min 1Q Median 3Q Max
## -122.61 -98.16 -42.61 20.84 879.60
##
## Coefficients:
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 121.6277 13.5185 8.997 1.87e-15 ***
## diagtime_c -0.6903 1.2785 -0.540 0.59
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Residual standard error: 158.2 on 135 degrees of freedom
## Multiple R-squared: 0.002155, Adjusted R-squared:
-0.005237
## F-statistic: 0.2915 on 1 and 135 DF, p-value: 0.5902</code></pre>
<p>From the model, it is clear that when diagtime and karno scores are 0, survival time is 123.37494 days. For every monthly increase in diag time, survival time increased by 1.09409 days. For every unit increase in karno score, survival time increased by 3.08128 days. For every increase in diag time (by month) and karno score (by single units), survival time increased by 0.04505 days. In reference to my above graphs and tests, it is clear that the assumption for regression (linearity,homoskedsaticity, normality) were not upheld; my predictors graph (karno_c and diagtime_c) and residuals graphs do not appear to be normaly distributed - no even scatter of points up the line and the residuals graph has unequal variance (points fan out towards the right). The robust standard errors are greater than my original standard errors. The proportion of variation in the outcome that my model explains is 0.1493513. My regresssion with interaction indicates that the karno score is a significant predictor (p-val= 4.39e-06).</p>
<pre class="r"><code>##Question 4


samp_distn&lt;-replicate(5000, {
 boot_dat&lt;-veteran[sample(nrow(veteran),replace=TRUE),]
 fit3&lt;-lm(time ~ diagtime_c * karno_c,data=boot_dat)
 coef(fit3)
})


samp_distn%&gt;%t%&gt;%as.data.frame%&gt;%summarize_all(sd)</code></pre>
<pre><code>##   (Intercept) diagtime_c   karno_c diagtime_c:karno_c
## 1    13.54025   1.599296 0.6832463         0.06457346</code></pre>
<p>In terms of the SEs, my boostrapped standard errors are slightly bigger than my original SEs and robust SEs. My p-values do not display any change.</p>
<pre class="r"><code>##Question 5

veteran$karnostatus&lt;-ifelse(veteran$karno&gt;50,1,0)

fitted4&lt;-glm(karnostatus~time+age,data=veteran,family=binomial(link=&quot;logit&quot;))

coeftest(fitted4)</code></pre>
<pre><code>##
## z test of coefficients:
##
## Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept) -0.1463136 1.0668570 -0.1371 0.8909166
## time 0.0098452 0.0027765 3.5459 0.0003913 ***
## age -0.0044185 0.0176275 -0.2507 0.8020755
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>exp(coef(fitted4))</code></pre>
<pre><code>## (Intercept)        time         age 
##   0.8638867   1.0098938   0.9955912</code></pre>
<pre class="r"><code>veteran$predicted&lt;-predict(fitted4, data=veteran, type = &quot;response&quot;)

table(predict=as.numeric(veteran$predicted&gt;.5),truth=veteran$karnostatus)%&gt;%addmargins</code></pre>
<pre><code>##        truth
## predict   0   1 Sum
##     0    36  15  51
##     1    16  70  86
##     Sum  52  85 137</code></pre>
<pre class="r"><code>(31+70)/137</code></pre>
<pre><code>## [1] 0.7372263</code></pre>
<pre class="r"><code>70/85</code></pre>
<pre><code>## [1] 0.8235294</code></pre>
<pre class="r"><code>31/46</code></pre>
<pre><code>## [1] 0.673913</code></pre>
<pre class="r"><code>70/91</code></pre>
<pre><code>## [1] 0.7692308</code></pre>
<pre class="r"><code>logit&lt;-predict(fitted4)

karnostatus &lt;-factor(veteran$karnostatus, levels = c(&quot;0&quot;,&quot;1
                                                     &quot;))
ggplot(veteran, aes(logit,fill=as.factor(karnostatus)))+geom_density(alpha=0.3)+geom_vline(xintercept = 0, lty=2)</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-6-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>library(plotROC)
ggplot(veteran,aes(time,predicted,color=age))+geom_line()</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-6-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>ROCplot&lt;-ggplot(veteran)+geom_roc(aes(d=karnostatus,m=predicted), n.cuts=0)+
 geom_segment(aes(x=0,xend=1,y=0,yend=1),lty=2)
ROCplot</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-6-3.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>calc_auc(ROCplot)</code></pre>
<pre><code>##   PANEL group       AUC
## 1     1    -1 0.7975113</code></pre>
<pre class="r"><code>class_diag&lt;-function(probs,truth){

tab&lt;-table(factor(probs&gt;.5,levels=c(&quot;FALSE&quot;,&quot;TRUE&quot;)),truth)
acc=sum(diag(tab))/sum(tab)
sens=tab[2,2]/colSums(tab)[2]
spec=tab[1,1]/colSums(tab)[1]
ppv=tab[2,2]/rowSums(tab)[2]

if(is.numeric(truth)==FALSE &amp; is.logical(truth)==FALSE) truth&lt;-as.numeric(truth)-1

ord&lt;-order(probs, decreasing=TRUE)
probs &lt;- probs[ord]; truth &lt;- truth[ord]

TPR=cumsum(truth)/max(1,sum(truth)) 
FPR=cumsum(!truth)/max(1,sum(!truth))

dup&lt;-c(probs[-1]&gt;=probs[-length(probs)], FALSE)
TPR&lt;-c(0,TPR[!dup],1); FPR&lt;-c(0,FPR[!dup],1)

n &lt;- length(TPR)
auc&lt;- sum( ((TPR[-1]+TPR[-n])/2) * (FPR[-1]-FPR[-n]) )

data.frame(acc,sens,spec,ppv,auc)
}

set.seed(1234)
k=10
data1&lt;-veteran[sample(nrow(veteran)),]
folds&lt;-cut(seq(1:nrow(veteran)),breaks=k,labels=F)
diags&lt;-NULL
for(i in 1:k){
train&lt;-data1[folds!=i,]
test&lt;-data1[folds==i,]
truth&lt;-test$karnostatus
fit6&lt;- glm(karnostatus~time+age,data=train,family=binomial(link=&quot;logit&quot;))
summary(fit6)
probs&lt;- predict(fit6, newdata=test, type=&quot;response&quot;)
diags&lt;-rbind(diags,class_diag(probs,truth))}
apply(diags,2,mean)</code></pre>
<pre><code>##       acc      sens      spec       ppv       auc 
## 0.7142857 0.7940693 0.6426190 0.7684848 0.7734730</code></pre>
<p>Controlling for age, for every unit increase in time (survival time, in days), the odds that a patient’s karno score was above 50 increased by a factor of 1.0094107. Controlling for time, for every unit increase in age (in years), the odds that a patient’s karno score was above 50 decreased by a factor of 0.9955912. My accuracy (proportion of correct classification) was 0.7372263, my specificity/TNR (proportion of status “0” with correct classification) was 0.673913, my sensitivity/TPR (proportion of status “1” with correct classification) was 0.8235294, my recall/PPV (proportion of pts with predicted of karno score&gt;50 who in actuality had a karno score&gt;50) was 0.7692308. My AUC was 0.7975113, which is considered acceptable for my predictors in predicting if a patient will have a karno score that is greater than 50. My 10 fold CV gave me average out-of-sample Accuracy, Sensitivity, and Recall of 0.7241758, 0.8057720, and 0.7633153, respectively.</p>
<pre class="r"><code>#Question 6

library(glmnet)

y&lt;-as.matrix(veteran$karno) 

x&lt;-veteran%&gt;%dplyr::select(diagtime, time, age, status, prior)%&gt;%mutate_all(scale)%&gt;%as.matrix

cv&lt;-cv.glmnet(x,y)

LASSO&lt;- glmnet(x,y,lambda = cv$lambda.1se)

coef(LASSO)</code></pre>
<pre><code>## 6 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                    s0
## (Intercept) 58.569343
## diagtime     .       
## time         1.298349
## age          .       
## status       .       
## prior        .</code></pre>
<pre class="r"><code>set.seed(1234)

k = 10
dat2 &lt;- veteran[sample(nrow(veteran)), ]

folds &lt;- cut(seq(1:nrow(veteran)), breaks = k, labels = F) 

diags &lt;- NULL

for (i in 1:k) {
train &lt;- dat2[folds != i, ]
test &lt;- dat2[folds == i, ]
fitted7 &lt;- lm(karno ~ time, data = train)
yhat &lt;- predict(fit6, newdata = test)
diags &lt;- mean((test$diagtime - yhat)^2) }
mean(diags)</code></pre>
<pre><code>## [1] 92.22762</code></pre>
<pre class="r"><code>summary(fitted7)</code></pre>
<pre><code>##
## Call:
## lm(formula = karno ~ time, data = train)
##
## Residuals:
## Min 1Q Median 3Q Max
## -45.365 -14.063 4.406 15.320 28.512
##
## Coefficients:
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 53.17222 2.06600 25.737 &lt; 2e-16 ***
## time 0.04569 0.01000 4.568 1.19e-05 ***
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Residual standard error: 18.21 on 121 degrees of freedom
## Multiple R-squared: 0.1471, Adjusted R-squared: 0.1401
## F-statistic: 20.87 on 1 and 121 DF, p-value: 1.193e-05</code></pre>
<p>The only variable that was retained for my situation was the time variable (3.659913) illustrating its signficance in predicting a patient’s karno score. My residual standard error was 17.43; this is greater than my 10 fold CV standard error and indicates that this lasso model is not a better fit.</p>
</div>
