---
title: Resume
author: Mina Attia
date: '2019-12-15'
slug: resume
categories: []
tags: []
description: ''
---

## About me: 

My name is Mina Attia and I was born in Alexandria, Egypt. At age 11, I immigrated to the US and have been residing in Texas. My edcuational background is concentrated in the biological sciences and business. My interests include medicine, entrepreneurship, and politics. My work experience includes pharmacokinetics research, phlebotomy, and retail. My skills range from being trilingual (Arabic, English, French) to my ability to teamwork effectively. Some of my accomplishments include research  and educational awards.

## Resume

Mina Attia

attiamha@gmail.com

EDUCATION							

The University of Texas at Austin 
Bachelor of Science and Arts, Biology
Minor in Business
December 2019


EXPERIENCE	 													

Pharmaceutical Product Development – Pharmacokinetics Research Lab Tech; Austin, TX June 2017- present 
•	Centrifuge blood samples from dosed patients and carry out chemical testing
•	Review completed research logs before submission to the quality control unit
•	Certified in blood harvesting and pipette precision

The University of Texas at Austin – Teaching Assistant; Austin, TX				      August 2017 - present
•	Instructor assistant to Dr. Mary Poteet for the Research Methods course under the Freshman Research Initiative program
•	Teach students laboratory techniques and guide them throughout their research experiments
•	Grade students’ research papers/assignments and provide constructive feedback

Auction Source Austin – Technology Technician; Austin, TX                     September 2016 – present
•	Oversee and troubleshoot any software system or WLAN issues during auction events
•	Train volunteers to assist with guest registration and guest check out
•	Provide event progress reports to the Chairs of the auction

Target – Front Sales Trainer and Guest Service; Georgetown, TX				            July 2015 – June 2017
•	Educated guests about the RedCard program and handled enrollments
•	Trained new front-end employees on payment system and being genuinely hospitable to all guests
•	 Handled guest service inquiries and was cross trained in several departments

ACADEMIC PROJECTS	 												

Research on the Effects of Carbon and Nitrogen on Allelic Variants of Arabidopsis		                   Spring 2017-  Fall 2017
•	Conducted research with the BioFuels department under Dr. Brandon Campitelli
•	Worked with a student researcher to set up the methods and analyses, then carried out a final experiment independently
•	Discovered patterns in which the LER and NIL genotypes responded to varying nutrient levels under stress

Research on the Effects of Tryptophan Exposure on the Social Behavior of Male Crickets			              Fall 2016
•	Researched with another FRI student under the guidance of Dr. Mary Poteet and a post-doctoral fellow
•	Discovered a trend relating observed aggressiveness to tryptophan exposure through the use of statistical analysis of data

LEADERSHIP EXPERIENCE AND ACTIVITIES				

Chemistry Learning Assistant										         Spring 2018
•	Facilitated discussions in the classroom to help 300+ students learn general chemistry
•	Attended weekly meetings with Dr. Stacy Sparks to practice/discuss ethics, values, and needs of students
•	Helped lead office hours and study halls where I learned to diversify my teaching strategies

Delta Epsilon Mu - Honoree / Member 					            Fall 2018 – present
•	Selected to be part of a professional pre-health fraternity that is recognized by the State of Texas
•	Fundraise for 20/20/20, a philanthropy that raises money for eye surgeries to aid impoverished children in third world nations 

HONORS														

•	UT Austin Alpha Lambda Delta and Phi Eta Sigma National Honoree        Fall 2016 – present
•	UT Austin CNS Scholar Honoree										                       Spring 2018
•	University Honors										                                   Fall 2016 – present
                   
ADDITIONAL INFORMATION												

Computer Skills: R Studio, HTML, Java, Adobe Photoshop, MS Word, Excel, PowerPoint, Access, Publisher, Outlook
Certifications: Microsoft Office Excel Certification (2016), OSHA (2016)
Languages: Fluent in Arabic, proficient in French
Interests: Healthcare, Research, Business, Politics, and Car Improvement

